apiVersion: batch/v1
kind: Job
metadata:
  name: machine-job-processor-view-projection-job-v3
spec:
  template:
    spec:
      containers:
      - name: achine-job-processor-view-projection
        image: ghcr.io/kolotree/machine-job-processor-view-projection:1.1
        env:
          - name: EventStore_ConnectionString
            value: "https://culaja.com:2111"
          - name: EventStore_Credentials
            value: "admin:changeit"
          - name: Projection_Name
            value: "MachineJobProcessorViewProjection"
      imagePullSecrets:
      - name: githubregistry
      restartPolicy: OnFailure
  backoffLimit: 100
