version: '3.7'
services:
  mongo:
    image: "mongo:latest"
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=kolotree'
      - 'MONGO_INITDB_ROOT_PASSWORD=kolotree4532'
