version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  complete-machine-job:
    lang: csharp-http-command
    handler: ./complete-machine-job
    image: ghcr.io/kolotree/complete-machine-job:1.2
  detect-machine-cycles:
    lang: csharp-http-command
    handler: ./detect-machine-cycles
    image: ghcr.io/kolotree/detect-machine-cycles:1.1
  detect-machine-start:
    lang: csharp-http-command
    handler: ./detect-machine-start
    image: ghcr.io/kolotree/detect-machine-start:1.1
  detect-machine-stop:
    lang: csharp-http-command
    handler: ./detect-machine-stop
    image: ghcr.io/kolotree/detect-machine-stop:1.1
  request-new-machine-job:
    lang: csharp-http-command
    handler: ./request-new-machine-job
    image: ghcr.io/kolotree/request-new-machine-job:1.1
