apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-job-processor-deployment
  labels:
    app: machine-job-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-job-processor
  template:
    metadata:
      labels:
        app: machine-job-processor
    spec:
      containers:
      - name: machine-job-processor
        image: ghcr.io/kolotree/machine-job-processor:1.1
        env:
          - name: EventStore__ConnectionString
            value: "esdb://culaja.com:2111,culaja.com:2112,culaja.com:2113?tls=true&tlsVerifyCert=false"
      imagePullSecrets:
      - name: githubregistry

