name: Build functions

on:
  push:
    paths:
      - 'src/functions/stack.yml'

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Get faas-cli
      run: curl -sLSf https://cli.openfaas.com | sudo sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Pull csharp-http-command template
      uses: docker://openfaas/faas-cli:latest-root
      with: 
        args: template pull https://culaja:${{secrets.FAAS_TEMPLATE_TOKEN}}@github.com/kolotree/EventModelingJobProcessingFaasTemplates
    - name: Build functions
      run: |
        cd ./src/functions
        faas-cli build
    - name: Login to GitHub container registry
      run: > 
        echo ${{secrets.GITHUB_TOKEN}} | 
        docker login docker.pkg.github.com --username 
        ${{ github.repository_owner }} 
        --password-stdin
    - name: Publish functions
      run: |
        cd ./src/functions
        faas-cli push
    - name: Login
      run: >
        echo ${{secrets.OPENFAAS_PASSWORD}} | 
        faas-cli login --gateway ${{secrets.OPENFAAS_URL}} --password-stdin
    - name: Deploy
      run: |
        cd ./src/functions
        OWNER="${{ github.repository_owner }}" faas-cli deploy --gateway ${{secrets.OPENFAAS_URL}}
