name: Build functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Copy functions to root directory
      run: |
        cp -r src/functions/* ./
    - name: Pull csharp-http-command template
      uses: docker://openfaas/faas-cli:latest-root
      with: 
        args: template pull https://culaja:${{secrets.FAAS_TEMPLATE_TOKEN}}@github.com/kolotree/EventModelingJobProcessingFaasTemplates
    - name: Build all functions
      uses: docker://openfaas/faas-cli:latest-root
      with: 
        args: build -shrinkwrap
    - name: Push new images
      uses: docker://openfaas/faas-cli:latest-root
      with: 
        args: push
