name: Build and publish processors

on:
  push:
    paths:
      - 'src/processors/docker-compose.yml'

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build processors
      run: |
        cd ./src/processors
        docker-compose build
    - name: Login to GitHub container registry
      run: > 
        echo ${{secrets.PRIVATE_GITHUB_REGISTRY}} | 
        docker login ghcr.io --username 
        ${{ github.repository_owner }} 
        --password-stdin
    - name: Publish functions
      run: |
        cd ./src/processors
        docker-compose push
