name: Build and publish functions

on:
  push:
    paths:
      - 'src/functions/stack.yml'

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Get faas-cli
      run: curl -sLSf https://cli.openfaas.com | sudo sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build functions
      run: |
        cd ./src/functions
        faas-cli template pull https://culaja:${{secrets.FAAS_TEMPLATE_TOKEN}}@github.com/kolotree/EventModelingJobProcessingFaasTemplates
        faas-cli build
    - name: Login to GitHub container registry
      run: > 
        echo ${{secrets.PRIVATE_GITHUB_REGISTRY}} | 
        docker login ghcr.io --username 
        ${{ github.repository_owner }} 
        --password-stdin
    - name: Publish functions
      run: |
        cd ./src/functions
        faas-cli push
