name: Build functions

on:
  push:
    paths:
      - 'deployment/production/functions-stack.yml'

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Get faas-cli
      run: curl -sLSf https://cli.openfaas.com | sudo sh
    - name: Login to culaja.com openfaas
      run: |
        cd ./src/functions
        echo ${{secrets.OPENFAAS_PASSWORD}} | faas-cli login --gateway ${{secrets.OPENFAAS_URL}} --password-stdin
    - name: Deploy functions to culaja.com openfaas
      run: |
        cd ./src/functions
        faas-cli template pull https://culaja:${{secrets.FAAS_TEMPLATE_TOKEN}}@github.com/kolotree/EventModelingJobProcessingFaasTemplates
        OWNER="${{ github.repository_owner }}" faas-cli deploy -f ../../deployment/production/functions-stack.yml --gateway ${{secrets.OPENFAAS_URL}}
